---
name: json-schema
on: workflow_call
jobs:
  json-schema:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - uses: aquaproj/registry-action/validate-json-schema@63f797c47a1c66ecf7a4bc4e07eb41360249190a # v0.2.4
